### ISSUE TITLE
Check Lambda Referenzen (in ADB) and maybe remove the implementation

### ISSUE THREAD

**Issue by mhus** [mhus/mhus-lib#19]
Lambda Method name loading is not functional in any cases, e.g. in osgi 

java.lang.NoClassDefFoundError: de/mhus/lib/core/util/lambda/RecordingObject
 at de.mhus.lib.adb.query.AQuery.initRecorder(AQuery.java:723)
 at de.mhus.lib.adb.query.AQuery.toAttributeName(AQuery.java:704)
 at de.mhus.lib.adb.query.AQuery.eq(AQuery.java:180)

**Comment by mhus** [comment]
changed way to get method name.
