### ISSUE TITLE
Fix exception if form field is read only

### ISSUE THREAD

**Issue by mhus** [mhus/mhus-lib#26]
at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2018-11-30 10:21:46,739 | ERROR | n/UIDL/?v-uiId=1 | VaadinFormBuilder                | 88 - mhu-lib-core - 3.3.7 | (67)[type]
com.vaadin.data.Property$ReadOnlyException
        at com.vaadin.ui.AbstractField.setValue(AbstractField.java:493)[64:com.vaadin.server:7.7.9]
        at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)[64:com.vaadin.server:7.7.9]
        at com.vaadin.ui.AbstractField.setValue(AbstractField.java:453)[64:com.vaadin.server:7.7.9]
        at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:456)[64:com.vaadin.server:7.7.9]
        at de.mhus.lib.vaadin.form.UiText.setValue(UiText.java:32)[92:mhu-lib-vaadin:3.3.7]
        at de.mhus.lib.vaadin.form.UiVaadin.doUpdateValue(UiVaadin.java:65)[92:mhu-lib-vaadin:3.3.7]
        at de.mhus.lib.vaadin.form.VaadinFormBuilder.doUpdateValues(VaadinFormBuilder.java:101)[92:mhu-lib-vaadin:3.3.7]
        at de.mhus.lib.vaadin.form.VaadinPojoForm.setPojo(VaadinPojoForm.java:39)[92:mhu-lib-vaadin:3.3.7]
        at de.mhus.lib.vaadin.AbstractListEditor.doUpdate(AbstractListEditor.java:428)[92:mhu-lib-vaadin:3.3.7]
        at de.mhus.lib.vaadin.AbstractListEditor.doUpdate(AbstractListEditor.java:341)[92:mhu-lib-vaadin:3.3.7]
        at de.mhus.lib.vaadin.AbstractListEditor$6.buttonClick(AbstractListEditor.java:180)[92:mhu-lib-vaadin:3.3.7]
        at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)

**Comment by mhus** [comment]
Use FaReadOnly instead of FaDisable
