### ISSUE TITLE
Logger error message while updating loggers

### ISSUE THREAD

**Issue by mhus** [mhus/mhus-lib#6]
java.lang.ArrayStoreException: java.util.UUID
	at java.util.AbstractCollection.toArray(AbstractCollection.java:195)[:1.7.0_79]
	at de.mhus.lib.core.MSingleton.updateLoggers(MSingleton.java:93)
	at de.mhus.lib.core.system.DefaultConfigLoader.reConfigure(DefaultConfigLoader.java:123)
	at de.mhus.lib.mutable.KarafSingletonImpl.reConfigure(KarafSingletonImpl.java:139)
	at de.mhus.lib.mutable.KarafSingletonImpl.doInitialize(KarafSingletonImpl.java:86)
	at de.mhus.lib.core.MSingleton.get(MSingleton.java:44)
	at de.mhus.lib.core.MSingleton.isTrace(MSingleton.java:64)
	at de.mhus.lib.core.logging.Log.<init>(Log.java:39)[159:mhu-lib-core:3.2.9.SNAPSHOT]
	at de.mhus.lib.core.logging.Log.getLog(Log.java:247)[159:mhu-lib-core:3.2.9.SNAPSHOT]
	at de.mhus.lib.karaf.services.TimerFactoryImpl.<init>(TimerFactoryImpl.java:24)

**Comment by mhus** [comment]
Fixed
